spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/social_platform
    username: root
    password: rootpass
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:

  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: false

    banner: false
  mapper-locations: classpath*:**/mappers/*Mapper.xml
  type-aliases-package: com.ghtt.socialplatform.domain

logging:
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 50MB
  file:
    path: D:/testlog/mylogs
    name: mylogs.log
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082
---
